name: dlhw3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - cudatoolkit=11.8  # Change to 11.7 or 12.1 depending on your GPU
  # Install via conda for better compatibility
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.2.0
  - tqdm>=4.65.0
  - pip:
    # PyTorch (install via pip for specific CUDA version)
    - torch>=2.0.0
    - torchvision>=0.15.0
    - torchaudio>=2.0.0
    # Hugging Face ecosystem
    - transformers>=4.30.0
    - datasets>=2.12.0
    - accelerate>=0.20.0
    - evaluate>=0.4.0
    - tokenizers>=0.13.0
    # Experiment tracking
    - wandb>=0.15.0
    # Additional utilities
    - sentencepiece>=0.1.99
    - protobuf>=3.20.0
